# Most Favorable Area to Open a Restaurant in the UK

This project will consist of an exploration of the way venues are distributed in three of the biggest cities in the UK. This will act as a reference for anyone interested in starting a business. For the purpose of this project, the main focus will be regarding finding the best place to start a restaurant. An entrepreneur interested in such investement can make use of this project by, either, picking the location with the least amount of opened restaurants (to prevent fearse competition), or choosing to invest in the city with the most opened restaurants (which could be a sign that such investment is popular among residents).

The data used will consist of:  
* Postcodes dataframes of the three UK cities
* Coordinates dataframes
* Foursquare dataframe of the venues

The methodology of this project will be putting the venues into Clusters using KMeans

## Importing the Data

In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans



print('Libraries imported.')

Libraries imported.

In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

# scraping
url = 'https://en.wikipedia.org/wiki/List_of_postcode_areas_in_the_United_Kingdom'

html_doc = urlopen(url)

soup = BeautifulSoup(html_doc, 'lxml')

In [3]:
# get the data from the table and upload it to kanj_data
table = soup.find("table", class_="wikitable")

kanj_data = []
for items in table.find_all("tr")[:-1]:
    data = [' '.join(item.text.split()) for item in items.find_all(['th','td'])]
    
    kanj_data.append(data)

In [13]:
# naming columns
df = pd.DataFrame(kanj_data, columns=['postcode','city','remove1','remove2'])
del df['remove1']
del df['remove2']
df.drop(0, axis=0, inplace=True)
df

    postcode                       city
1         AB                   Aberdeen
2         AL                  St Albans
3          B                 Birmingham
4         BA                       Bath
5         BB                  Blackburn
6         BD                   Bradford
7         BH                Bournemouth
8         BL                     Bolton
9         BN                   Brighton
10        BR                    Bromley
11        BS                    Bristol
12        BT                    Belfast
13        CA                   Carlisle
14        CB                  Cambridge
15        CF                    Cardiff
16        CH                    Chester
17        CM                 Chelmsford
18        CO                 Colchester
19        CR                    Croydon
20        CT                 Canterbury
21        CV                   Coventry
22        CW                      Crewe
23        DA                   Dartford
24        DD                     Dundee
25        DE                      Derby
26        DG                Dumfries[1]
27        DH                     Durham
28        DL                 Darlington
29        DN                  Doncaster
30        DT                 Dorchester
31        DY                     Dudley
32         E                East London
33        EC        East Central London
34        EH                  Edinburgh
35        EN                    Enfield
36        EX                     Exeter
37        FK                    Falkirk
38        FY               Blackpool[1]
39         G                    Glasgow
40        GL                 Gloucester
41        GU                  Guildford
42        HA                     Harrow
43        HD               Huddersfield
44        HG                  Harrogate
45        HP            Hemel Hempstead
46        HR                   Hereford
47        HS                   Hebrides
48        HU                       Hull
49        HX                    Halifax
50        IG                     Ilford
51        IP                    Ipswich
52        IV                  Inverness
53        KA                 Kilmarnock
54        KT       Kingston upon Thames
55        KW                   Kirkwall
56        KY                  Kirkcaldy
57         L                  Liverpool
58        LA                  Lancaster
59        LD       Llandrindod Wells[1]
60        LE                  Leicester
61        LL                  Llandudno
62        LN                    Lincoln
63        LS                      Leeds
64        LU                      Luton
65         M                 Manchester
66        ME                     Medway
67        MK              Milton Keynes
68        ML                 Motherwell
69         N               North London
70        NE  Newcastle upon Tyne[4][5]
71        NG                 Nottingham
72        NN                Northampton
73        NP                    Newport
74        NR                    Norwich
75        NW          North West London
76        OL                     Oldham
77        OX                     Oxford
78        PA                    Paisley
79        PE               Peterborough
80        PH                      Perth
81        PL                   Plymouth
82        PO                 Portsmouth
83        PR                    Preston
84        RG                    Reading
85        RH                    Redhill
86        RM                    Romford
87         S                  Sheffield
88        SA                    Swansea
89        SE          South East London
90        SG                  Stevenage
91        SK                  Stockport
92        SL                     Slough
93        SM                  Sutton[1]
94        SN                    Swindon
95        SO                Southampton
96        SP                  Salisbury
97        SR                 Sunderland
98        SS            Southend-on-Sea
99        ST             Stoke-on-Trent
100       SW          South West London
101       SY                 Shrewsbury
102       TA                    Taunton
103       TD                  Tweeddale
104       TF                    Telford
105       TN         Tunbridge Wells[1]
106       TQ                    Torquay
107       TR                      Truro
108       TS                    Teeside
109       TW                 Twickenham
110       UB                Southall[1]
111        W                West London
112       WA                 Warrington
113       WC     Western Central London
114       WD                    Watford
115       WF                  Wakefield
116       WN                      Wigan
117       WR                  Worcester
118       WS                    Walsall
119       WV              Wolverhampton
120       YO                       York